name: Install FFmpeg

on: [push]

jobs:
  install-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install FFmpeg
        run: |
          # Download the FFmpeg release tarball
          curl -Lo ffmpeg.tar.xz https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          
          # Extract FFmpeg
          tar -xvf ffmpeg.tar.xz
          
          # Make FFmpeg executable (assuming it's in the extracted directory)
          chmod +x ./ffmpeg

          # Move FFmpeg to a directory in PATH (e.g., /usr/local/bin)
          sudo mv ./ffmpeg /usr/local/bin/

      - name: Verify FFmpeg installation
        run: ffmpeg -version
