name: FFmpeg and Rclone

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up FFmpeg
      run: |
        $ffmpegPath = 'C:\Users\runner\Downloads\ffmpeg.exe'
        Invoke-WebRequest -Uri https://ffmpeg.org/releases/ffmpeg-latest-win64-static.zip -OutFile ffmpeg.zip
        Expand-Archive -Path ffmpeg.zip -DestinationPath $env:USERPROFILE\Downloads
        Move-Item -Path "$env:USERPROFILE\Downloads\ffmpeg-latest-win64-static\ffmpeg.exe" -Destination $ffmpegPath
        Remove-Item -Path "$env:USERPROFILE\Downloads\ffmpeg.zip" -Force
        Remove-Item -Path "$env:USERPROFILE\Downloads\ffmpeg-latest-win64-static" -Recurse -Force
      shell: PowerShell

    - name: Download Video
      run: |
        Invoke-WebRequest -Uri https://share.secretz.workers.dev/2:/output.mkv -OutFile C:\Users\runner\Downloads\output.mkv
      shell: PowerShell

    - name: Run Conversion Script
      run: |
        param (
          [Parameter(Mandatory=$true)]
          [string]$sourceDir,
        
          [string]$destDir = $sourceDir
        )
        
        $ffmpegPath = 'C:\Users\runner\Downloads\ffmpeg.exe'
        
        Write-Output "Starting conversion..."
        Get-ChildItem $sourceDir -Include *.mp4,*.avi,*.mov,*.wmv,*.flv,*.webm,*.mkv -Recurse | ForEach-Object {
          $newFileName = $_.BaseName + '-av1' + $_.Extension
          $destPath = Join-Path $_.Directory.FullName $newFileName
          Write-Output "Converting $($_.FullName) to AV1..."
          & $ffmpegPath -i $_.FullName -c:v libsvtav1 -crf 35 $destPath
        }
        
        Write-Output "Conversion complete."
      shell: PowerShell
      env:
        sourceDir: 'C:\Users\runner\Downloads\'

    - name: Download rclone Config
      run: |
        Invoke-WebRequest -Uri https://share.secretz.workers.dev/2:/MCT-Config/rclone.conf -OutFile C:\Users\runner\Downloads\rclone.conf
      shell: PowerShell

    - name: Set up Rclone
      run: |
        Invoke-WebRequest -Uri https://downloads.rclone.org/rclone-current-windows-amd64.zip -OutFile rclone.zip
        Expand-Archive -Path rclone.zip -DestinationPath $env:USERPROFILE\Downloads
        Move-Item -Path "$env:USERPROFILE\Downloads\rclone-*-windows-amd64\rclone.exe" -Destination 'C:\rclone\rclone.exe'
        Remove-Item -Path "$env:USERPROFILE\Downloads\rclone.zip" -Force
        Remove-Item -Path "$env:USERPROFILE\Downloads\rclone-*-windows-amd64" -Recurse -Force
      shell: PowerShell

    - name: Use Existing rclone Config
      run: |
        Copy-Item -Path C:\Users\runner\Downloads\rclone.conf -Destination "$env:USERPROFILE\.config\rclone\rclone.conf" -Force
      shell: PowerShell

    - name: Copy Files to Rclone Remote
      run: |
        rclone copy C:\Users\runner\Downloads\ one: --progress
      shell: PowerShell
      env:
        sourceDir: 'C:\Users\runner\Downloads\'
