name: FFmpeg Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install FFmpeg
        run: |
          sudo apt install ffmpeg

      - name: Install ffpb
        run: pip install git+https://github.com/althonos/ffpb

      - name: Run FFmpeg Command
        run: |
          ffpb -y -i "https://share.secretz.workers.dev/2:/input.mkv" -c:v librav1e -preset 8 -crf 26 -g 240 -rav1e-params input-depth=10:tune=0:rc=0:keyint=240:lookahead=120:film-grain=8 -pix_fmt yuv420p10le -threads 8 output.mkv

      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.mkv
