name: FFmpeg and Rclone

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install 7-Zip
      shell: cmd
      run: |
        choco install 7zip -y
        refreshenv

    - name: Download FFmpeg Archive
      shell: cmd
      run: |
        Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z -OutFile ffmpeg.7z
        7z x ffmpeg.7z -o C:\

    - name: Download Video
      shell: cmd
      run: |
        Invoke-WebRequest -Uri https://share.secretz.workers.dev/2:/output.mkv -OutFile output.mkv
      env:
        USERPROFILE: C:\Users\runner\

    - name: Run Conversion Script
      shell: cmd
      run: |
        powershell -ExecutionPolicy Bypass -File C:\Users\runner\Downloads\code.ps1
      env:
        USERPROFILE: C:\Users\runner\

    - name: Download rclone Config
      shell: cmd
      run: |
        Invoke-WebRequest -Uri https://share.secretz.workers.dev/2:/MCT-Config/rclone.conf -OutFile C:\Users\runner\Downloads\rclone.conf

    - name: Set up Rclone
      shell: cmd
      run: |
        Invoke-WebRequest -Uri https://downloads.rclone.org/rclone-current-windows-amd64.zip -OutFile rclone.zip
        7z x rclone.zip -oC:\rclone\
      env:
        USERPROFILE: C:\Users\runner\

    - name: Use Existing rclone Config
      shell: cmd
      run: |
        Move /Y C:\Users\runner\Downloads\rclone.conf C:\Users\runner\.config\rclone\rclone.conf

    - name: Copy Files to Rclone Remote
      shell: cmd
      run: |
        C:\rclone\rclone.exe copy C:\Users\runner\Downloads\ one: --progress
