name: Install FFmpeg

on: [push]

jobs:
  install-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download FFmpeg
        run: |
          sudo apt install p7zip curl
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          cd /usr/local/bin/
          cd /usr/local/bin/ && 7z e /usr/local/bin/ffmpeg.tar.xz
          cd /usr/local/bin/ && 7z e /usr/local/bin/ffmpeg.tar
          cd /usr/local/bin/ && sudo chmod a+rx /usr/local/bin/ffmpeg
          
      - name: Navigate to /content/
        run: ffmpeg -version
       
      - name: Install ffpb
        run: pip install git+https://github.com/althonos/ffpb

      - name: Run FFmpeg Command
        run: |
          ffpb -y -i "https://share.secretz.workers.dev/2:/input.mkv" -c:v libx265 -preset slow -pix_fmt yuv420p10le -tune film -profile:v main10 -c:a copy -x265-params pass=1 /dev/null && ffpb -y -i "https://share.secretz.workers.dev/2:/input.mkv" -c:v libx265 -preset slow -pix_fmt yuv420p10le -tune film -profile:v main10 -c:a copy -x265-params pass=2 output.mkv  

      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.mkv
