name: Install FFmpeg

on: [push]

jobs:
  install-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download FFmpeg
        run: |
          sudo apt install p7zip curl
          mkdir /usr/local/bin/
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          cd /usr/local/bin/
          cd /usr/local/bin/ && 7z e /usr/local/bin/ffmpeg.tar.xz
          cd /usr/local/bin/ && 7z e /usr/local/bin/ffmpeg.tar
          cd /usr/local/bin/ && sudo chmod a+rx /usr/local/bin/ffmpeg
          
      - name: Navigate to /content/
        run: ffmpeg -version
